version: 2

default_config: &default_config
  docker:
    - image: cypress/included:4.8.0
  working_directory: ~/qa-slack-poc

pr-review_filters: &pr-review_filters
  branches:
    only:
      - /scenario.*/

production_filters: &production_filters
  branches:
    only:
      - master

jobs:
  Replace_Keys:
    <<: *default_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Replace Keys
          command: bash cypress/Utils/PreTest.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  Run_Lint:
    <<: *default_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run ESLint
          command: npm run lint

  Run_Tests:
    <<: *default_config
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Reporter
          command: npm install mochawesome --save-dev
      - run:
          name: Run Backend Tests
          command: npm run test:backend
      - run:
          name: Run E2E Tests
          command: npm run test:ci


workflows:
  version: 2
  pre-commit-checks:
    jobs:
      - Run_Lint:
          filters: *pr-review_filters
      - Run_Tests:
          requires:
            - Run_Lint
            - Replace_Keys
          filters: *pr-review_filters
  
  post-commit-checks_production:
    jobs:
      - Run_Lint:
          filters: *production_filters
      - Run_Tests:
          requires:
            - Run_Lint
          filters: *production_filters