version: 2

default_config: &default_config
  docker:
    - image: cypress/included:4.8.0
  working_directory: ~/qa-slack-poc

pr-review_filters: &pr-review_filters
  branches:
    only:
      - /scenario.*/

production_filters: &production_filters
  branches:
    only:
      - master

jobs:
  Run_Lint:
    <<: *default_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cypress.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "cypress.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run ESLint
          command: npm run lint

  Run_Backend_Tests:
    <<: *default_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cypress.json" }}
      - run:
          name: Populate Backend Keys
          command: bash cypress/Utils/PreTest.sh
      - run:
          name: Run Backend Tests
          command: npm run test:backend
      - persist_to_workspace:
          root: ./
          paths:
            - cypress/backend      
      - save_cache:
          key: dependency-cache-{{ checksum "cypress.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  Run_E2E_Tests:
    <<: *default_config
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cypress.json" }}
      - run:
          name: Install Reporter
          command: npm install mochawesome --save-dev
      - run:
          name: Run E2E Tests
          command: npm run test:ci

workflows:
  version: 2
  pre-commit-checks:
    jobs:
      - Run_Lint:
          filters: *pr-review_filters
      - Run_Backend_Tests:
          requires:
            - Run_Lint
          filters: *pr-review_filters
      - Run_E2E_Tests:
          requires:
            - Run_Lint
            - Run_Backend_Tests
          filters: *pr-review_filters

  
  post-commit-checks_production:
    jobs:
      - Run_Lint:
          filters: *production_filters
      - Run_Tests:
          requires:
            - Run_Lint
          filters: *production_filters